# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "4T2023" ]
  pull_request:
    branches: [ "4T2023" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.20', '1.18','>=1.20']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: go build -v ./...

    - name: docker-compose
      run: docker-compose up -d

    - name: Test
      run: go test -v ./...
