# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "4T2023" ]
  pull_request:
    branches: [ "4T2023" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.20', '1.18','>=1.20']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: go build -v main.go

    - name: docker-compose
      run: docker-compose up -d

    - name: Test
      run: go test -v main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: programa_go
        # A file, directory or wildcard pattern that describes what to upload
        path: main

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: programa_go

    - name: Docker Login

      uses: docker/login-action@v3.0.0
      with:
        username: leonardosartorello
        password: ${{ secrets.SENHA_DOCKER }}
    
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: leonardosartorello/livecode_ci:${{ github.run_number }}







    
